services:
  camera-wdg-web:
    image: nginx:latest
    volumes:
      - ${HOST_OUTPUT_DIR}:/www/streams:ro
      - ./views:/www/views:ro
      - ./static:/www/static:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro   # use gen_htpassword.py to generate
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${WEB_PORT}:80
    restart: unless-stopped

  camera-wdg-main:
    build:
      context: ./camwatchdog
    volumes:
      - ${HOST_OUTPUT_DIR}:/streams
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OUTPUT_DIR=/streams
      - TARGET_CLIP_LENGTH_SECONDS=${TARGET_CLIP_LENGTH_SECONDS}
      - KEEP_HOURS=${KEEP_HOURS}
    restart: unless-stopped
